---
version: "3.8"

services:
  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:latest"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=uaa-core
    command: --default-authentication-plugin=mysql_native_password
